title: Carrawayang
description: ML, DL, HPC
lang: zh-CN
author: Cay
google_analytics: 
show_downloads: false
paginate: 20
baseurl: ""
permalink: none

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-toc

markdown: kramdown
exclude: ["README.md"]

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      toc: true
